/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import apoio.Mensagem;
import controladores.ControlaAnime;
import entidades.Anime;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 * 
 * @author samuel.ogliari
 */
public class TelaAnime extends javax.swing.JFrame {

    private final ControlaAnime controladorAnime = new ControlaAnime();
    int codigo = 0;

    public TelaAnime() {
        initComponents();
        setLocationRelativeTo(null);
        spnAno.setValue(2000);
        montaTabela();
    }

    private void montaTabela() {
        ArrayList<Anime> animes = controladorAnime.recuperarTodos();

        String[] colunas = {
            "ID", "Título", "Gênero", "Estudio", "Ano", "Tem Mangá", "Tem Dublagem"
        };

        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);

        for (int i = 0; i < animes.size(); i++) {
            Anime anime = animes.get(i);

            Object[] linha = {
                anime.getCodigo(),
                anime.getTitulo(),
                anime.getGenero(),
                anime.getEstudio(),
                anime.getAnoLancamento(),
                anime.isTemManga(),
                anime.isDublado()
            };

            modelo.addRow(linha);
        }

        tblItens.setModel(modelo);

        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblItens.getColumnCount(); i++) {
            tblItens.getColumnModel().getColumn(i).setCellRenderer(centralizado);
        }

        tblItens.getColumnModel().getColumn(0).setMinWidth(15);
        tblItens.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblItens.getColumnModel().getColumn(0).setMaxWidth(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLtitulo = new javax.swing.JLabel();
        JLgenero = new javax.swing.JLabel();
        JLanoLancamento = new javax.swing.JLabel();
        JLestudio = new javax.swing.JLabel();
        JLmanga = new javax.swing.JLabel();
        JLdublagem = new javax.swing.JLabel();
        cbDublado = new javax.swing.JComboBox<>();
        cbTemManga = new javax.swing.JComboBox<>();
        txtEstudio = new javax.swing.JTextField();
        spnAno = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        txtGenero = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnGerenciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        JLtitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo.setText("Titulo:");
        JLtitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLtituloMouseClicked(evt);
            }
        });

        JLgenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLgenero.setForeground(new java.awt.Color(255, 255, 255));
        JLgenero.setText("Gênero:");
        JLgenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLgeneroMouseClicked(evt);
            }
        });

        JLanoLancamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLanoLancamento.setForeground(new java.awt.Color(255, 255, 255));
        JLanoLancamento.setText("Ano do Lançamento:");
        JLanoLancamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLanoLancamentoMouseClicked(evt);
            }
        });

        JLestudio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLestudio.setForeground(new java.awt.Color(255, 255, 255));
        JLestudio.setText("Estudio:");
        JLestudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLestudioMouseClicked(evt);
            }
        });

        JLmanga.setText("O anime tem mangá?");
        JLmanga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLmangaMouseClicked(evt);
            }
        });

        JLdublagem.setText("Ele tem dublagem?");
        JLdublagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLdublagemMouseClicked(evt);
            }
        });

        cbDublado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        cbTemManga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItens);

        btnSalvar.setBackground(new java.awt.Color(153, 153, 153));
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 0, 51));
        btnExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(204, 204, 204));
        btnListar.setForeground(new java.awt.Color(0, 0, 0));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Reload_1.png"))); // NOI18N
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(204, 255, 204));
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnGerenciar.setBackground(new java.awt.Color(102, 0, 102));
        btnGerenciar.setForeground(new java.awt.Color(255, 255, 255));
        btnGerenciar.setText("Gerenciar Elenco");
        btnGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGenero))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLanoLancamento)
                                    .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnExcluir)
                                        .addGap(62, 62, 62)
                                        .addComponent(btnGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSalvar)
                                    .addComponent(btnEditar)))
                            .addComponent(JLtitulo)
                            .addComponent(JLgenero)
                            .addComponent(JLestudio)
                            .addComponent(txtEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnListar)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDublado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTemManga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLmanga)
                            .addComponent(JLdublagem))
                        .addGap(54, 54, 54)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLtitulo)
                    .addComponent(JLmanga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTemManga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLgenero)
                    .addComponent(JLdublagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDublado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JLestudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(JLanoLancamento)
                .addGap(18, 18, 18)
                .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditar)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnVoltar)
                    .addComponent(btnGerenciar))
                .addGap(24, 24, 24))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Anime anime = new Anime(
                txtTitulo.getText(),
                txtGenero.getText(),
                txtEstudio.getText(),
                cbTemManga.getSelectedItem().toString().equals("Sim"),
                cbDublado.getSelectedItem().toString().equals("Sim"),
                (int) spnAno.getValue()
        );

        if (codigo == 0) {
            controladorAnime.salvar(anime);
        } else {
            anime.setCodigo(codigo);
            controladorAnime.editar(anime);
            codigo = 0;
        }

        btnSalvar.setText("Salvar");
        montaTabela();

        txtTitulo.setText("");
        txtGenero.setText("");
        txtEstudio.setText("");
        spnAno.setValue(0);
        cbTemManga.setSelectedItem("Sim");
        cbDublado.setSelectedItem("Sim");

        txtTitulo.requestFocus();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idString = String.valueOf(
                tblItens.getValueAt(tblItens.getSelectedRow(), 0)
        );

        int id = Integer.parseInt(idString);

        Anime anime = controladorAnime.recuperarUm(id);

        if (anime != null) {
            codigo = anime.getCodigo();

            txtTitulo.setText(anime.getTitulo());
            txtGenero.setText(anime.getGenero());
            txtEstudio.setText(anime.getEstudio());
            spnAno.setValue(anime.getAnoLancamento());
            cbTemManga.setSelectedItem(anime.isTemManga() ? "Sim" : "Não");
            cbDublado.setSelectedItem(anime.isDublado() ? "Sim" : "Não");

            btnSalvar.setText("Atualizar");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int confirmacao = Mensagem.confirmacao("Deseja realmente excluir?");

        if (confirmacao == 0) {
            int codigo = Integer.parseInt(
                    String.valueOf(tblItens.getValueAt(tblItens.getSelectedRow(), 0))
            );

            controladorAnime.excluir(codigo);
            montaTabela();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaMenu telaMenu = new TelaMenu();
        telaMenu.setVisible(true);
        this.dispose(); // fecha o menu atual
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        montaTabela();
    }//GEN-LAST:event_btnListarActionPerformed

    private void JLtituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLtituloMouseClicked
        txtTitulo.requestFocus();
    }//GEN-LAST:event_JLtituloMouseClicked

    private void JLgeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLgeneroMouseClicked
        txtGenero.requestFocus();
    }//GEN-LAST:event_JLgeneroMouseClicked

    private void JLestudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLestudioMouseClicked
        txtEstudio.requestFocus();
    }//GEN-LAST:event_JLestudioMouseClicked

    private void JLanoLancamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLanoLancamentoMouseClicked
        spnAno.requestFocus();
    }//GEN-LAST:event_JLanoLancamentoMouseClicked

    private void JLmangaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLmangaMouseClicked
        cbTemManga.requestFocus();
    }//GEN-LAST:event_JLmangaMouseClicked

    private void JLdublagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLdublagemMouseClicked
       cbDublado.requestFocus();
    }//GEN-LAST:event_JLdublagemMouseClicked

    private void btnGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarActionPerformed
        TelaAnimeElenco telaAnimeElenco = new TelaAnimeElenco();
        telaAnimeElenco.setVisible(true);
        this.dispose(); // fecha o menu atual
    }//GEN-LAST:event_btnGerenciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAnime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLanoLancamento;
    private javax.swing.JLabel JLdublagem;
    private javax.swing.JLabel JLestudio;
    private javax.swing.JLabel JLgenero;
    private javax.swing.JLabel JLmanga;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGerenciar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbDublado;
    private javax.swing.JComboBox<String> cbTemManga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnAno;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtEstudio;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
