/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author samuel.ogliari
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(32, 32, 32)); //conserta bug design aparecendo branco
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFilme1 = new javax.swing.JButton();
        btnAnime = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnElenco = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();
        ChupetaFlix = new javax.swing.JLabel();
        btnSerie1 = new javax.swing.JButton();
        btnFilme2 = new javax.swing.JButton();

        btnFilme1.setBackground(new java.awt.Color(51, 0, 0));
        btnFilme1.setForeground(new java.awt.Color(255, 255, 255));
        btnFilme1.setText("Filmes");
        btnFilme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilme1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnime.setBackground(new java.awt.Color(51, 0, 0));
        btnAnime.setForeground(new java.awt.Color(255, 255, 255));
        btnAnime.setText("Animes");
        btnAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimeActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(150, 0, 0));
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.setToolTipText("");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnElenco.setBackground(new java.awt.Color(0, 0, 0));
        btnElenco.setForeground(new java.awt.Color(255, 255, 255));
        btnElenco.setText("Elenco");
        btnElenco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElencoActionPerformed(evt);
            }
        });

        Imagem.setForeground(new java.awt.Color(51, 51, 51));
        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ChupetaFlix.png"))); // NOI18N

        ChupetaFlix.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        ChupetaFlix.setForeground(new java.awt.Color(255, 255, 255));
        ChupetaFlix.setText("CHUPETAFLIX");

        btnSerie1.setBackground(new java.awt.Color(0, 0, 0));
        btnSerie1.setForeground(new java.awt.Color(255, 255, 255));
        btnSerie1.setText("Séries");
        btnSerie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerie1ActionPerformed(evt);
            }
        });

        btnFilme2.setBackground(new java.awt.Color(51, 0, 0));
        btnFilme2.setForeground(new java.awt.Color(255, 255, 255));
        btnFilme2.setText("Filmes");
        btnFilme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilme2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnElenco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(btnAnime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSerie1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(btnFilme2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ChupetaFlix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Imagem)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Imagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChupetaFlix, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFilme2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSerie1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnElenco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimeActionPerformed
        TelaAnime telaAnime = new TelaAnime();
        telaAnime.setVisible(true);
        this.dispose(); // fecha o menu atual
    }//GEN-LAST:event_btnAnimeActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        this.dispose(); // fecha o menu atual
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnElencoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElencoActionPerformed
        TelaElenco telaElenco = new TelaElenco();
        telaElenco.setVisible(true);
        this.dispose(); // fecha o menu atual
    }//GEN-LAST:event_btnElencoActionPerformed

    private void btnSerie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerie1ActionPerformed
       TelaSerie telaSerie = new TelaSerie();
       telaSerie.setVisible(true);
       this.dispose(); //fecha o menu at..
    }//GEN-LAST:event_btnSerie1ActionPerformed

    private void btnFilme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilme1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilme1ActionPerformed

    private void btnFilme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilme2ActionPerformed
        TelaFilme telaFilme = new TelaFilme();
        telaFilme.setVisible(true);
        this.dispose(); // fecha o menu atual
    }//GEN-LAST:event_btnFilme2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChupetaFlix;
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton btnAnime;
    private javax.swing.JButton btnElenco;
    private javax.swing.JButton btnFilme1;
    private javax.swing.JButton btnFilme2;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSerie1;
    // End of variables declaration//GEN-END:variables
}
